# Generated by Django 4.0 on 2022-05-02 03:23

import annoying.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': []},
        ),
        migrations.RemoveField(
            model_name='personal_user_settings',
            name='rank',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Viewer', 'Viewer')], default='Viewer', max_length=10),
        ),
        migrations.AlterField(
            model_name='personal_user_settings',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to='app.customuser'),
        ),
        migrations.AlterField(
            model_name='recent_new_user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 3, 23, 10, 857531, tzinfo=utc), editable=False),
        ),
    ]
