# Generated by Django 4.0 on 2022-05-02 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='recent_new_user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 6, 56, 14, 615088, tzinfo=utc), editable=False),
        ),
    ]
