# Generated by Django 4.0 on 2022-05-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_item_stock_alter_item_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent_new_user',
            name='descrption',
            field=models.CharField(max_length=250),
        ),
    ]
